spring:
  application:
    name: async-taskor
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/async_taskor
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

application:
  storage:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
    bucket:
      src: ${MINIO_BUCKET_SRC:images-input}
      dst: ${MINIO_BUCKET_DST:images-output}
